name: Python CI Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        poetry-version: [1.1.7]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r saas/requirements_dev.txt
    - name: Lint with flake8
      run: pflake8 --config=saas/pyproject.toml saas
    - name: Lint with bandit
      run: bandit -c saas/pyproject.toml -r saas
    - name: Lint with mypy
      run:  mypy --config-file=saas/pyproject.toml saas
    - name: Test with pytest
      run: pytest -c saas/pyproject.toml saas
